### ISSUE TITLE
についてbubblesノード

### ISSUE THREAD

**Issue by XiaChong97** [gupon/Houdini-Gulib#1]
バブルノードの使用方法を教えてください。リンクは効果がありません。

**Comment by gupon** [comment]
I will planning to optimize the Bubbles HDA later, but it's easier to use [Remesh Bubbles SOP](https://www.sidefx.com/docs/houdini/nodes/sop/remeshbubbles.html), which works nearly the same.

**Comment by XiaChong97** [comment]
OK. Thank you.
